# Generated by Django 4.0.1 on 2022-01-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_io', '0002_alter_message_short_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='short_id',
            field=models.CharField(default='KKFN5ACTH', max_length=255),
        ),
    ]
